Repository GASIP-PROJECT/gasip-backend, pull requests merged in 2023-12, with the labels that each got.

#81 Feat: 게시글 작성 시 로그인 회원 인증 추가
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/dto/BoardCreateRequest.java
  src/main/java/com/example/gasip/board/dto/BoardCreateResponse.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/college/model/College.java
  src/main/java/com/example/gasip/member/dto/MemberMyPageRequest.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: enhancement, Backend

#86 Feat: Create SignUpPage, Add AuthStore using redux
  Gasip Front/App.js
  Gasip Front/Components/HomeStack.js
  Gasip Front/Components/MyPageScreen.js
  Gasip Front/Components/MyPageStack.js
  Gasip Front/Components/SignUpPage.js
  Gasip Front/Components/SplashScreen.js
  Gasip Front/Layout/layout.js
  Gasip Front/app.json
  Gasip Front/eas.json
  Gasip Front/package-lock.json
  Gasip Front/package.json
  Gasip Front/reducers/AuthStore.js
  Gasip Front/reducers/Authentication.js
  Gasip Front/reducers/reducer.js
Labels: enhancement, Frontend

#88 Refactor: Board/BoardDetail 도메인 병합 + yml 파일 복구
  src/main/java/com/example/gasip/Boarddetail/controller/BoardDetailController.java
  src/main/java/com/example/gasip/Boarddetail/model/BoardDetail.java
  src/main/java/com/example/gasip/Boarddetail/repository/BoardDetailRepository.java
  src/main/java/com/example/gasip/Boarddetail/service/BoardDetailService.java
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/dto/BoardDetailResponse.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/category/dto/CategoryDTO.java
  src/main/java/com/example/gasip/college/dto/CollegeResponse.java
  src/main/resources/templates/home.html
  src/main/resources/templates/professor/professorDetail.html
  src/main/resources/templates/professor/professorlist.html
Labels: enhancement, Backend

#92 Refactor: API 공통 포맷 적용
  src/main/java/com/example/gasip/HomeController.java
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/category/controller/CategoryController.java
  src/main/java/com/example/gasip/college/controller/CollegeController.java
  src/main/java/com/example/gasip/global/api/ApiError.java
  src/main/java/com/example/gasip/global/api/ApiResult.java
  src/main/java/com/example/gasip/global/api/ApiUtils.java
  src/main/java/com/example/gasip/member/controller/MemberController.java
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
  src/main/java/com/example/gasip/professordetail/controller/ProfessorDetailController.java
Labels: Backend, Refactoring

#95 Refactor: accessToken 유효시간 연장
  src/main/java/com/example/gasip/global/security/JwtService.java
Labels: Backend, Refactoring

#97 Feat: 사용자 로그인 페이지 구현 및 커스텀훅 적용
  .gitmessage
  Gasip Front/Components/HomeScreen.js
  Gasip Front/Components/MyPageScreen.js
  Gasip Front/Components/MyPageStack.js
  Gasip Front/Components/ProfList.js
  Gasip Front/Components/SignInPage.js
  Gasip Front/Components/SignUpPage.js
  Gasip Front/Components/ThemeStyle.js
  Gasip Front/Components/WritePage.js
  Gasip Front/Layout/layout.js
  Gasip Front/Utils/AuthFunc.js
  Gasip Front/Utils/AuthHooks.js
  Gasip Front/eas.json
Labels: enhancement, Frontend

#105 Feat: Board 수정/삭제 시 사용자 인증 로직 추가
  src/main/generated/com/example/gasip/board/dto/QBoardReadResponse.java
  src/main/generated/com/example/gasip/board/model/QBoard.java
  src/main/generated/com/example/gasip/category/model/QCategory.java
  src/main/generated/com/example/gasip/college/model/QCollege.java
  src/main/generated/com/example/gasip/comment/model/QComment.java
  src/main/generated/com/example/gasip/global/entity/QBaseTimeEntity.java
  src/main/generated/com/example/gasip/major/model/QMajor.java
  src/main/generated/com/example/gasip/member/model/QMember.java
  src/main/generated/com/example/gasip/professor/model/QProfessor.java
  src/main/generated/com/example/gasip/professordetail/model/QProfessorDetail.java
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/comment/dto/CommentDto.java
Labels: enhancement, Backend
