Repository GASIP-PROJECT/gasip-backend, pull requests merged in 2024-02, with the labels that each got.

#119 Feat : 토큰 만료여부 체크 메서드 개발
  src/main/java/com/example/gasip/member/controller/MemberController.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: enhancement, Backend

#123 Feature/#120 views
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/dto/BoardReadRequest.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/category/controller/CategoryController.java
  src/main/java/com/example/gasip/category/repository/CategoryRepository.java
  src/main/java/com/example/gasip/category/service/CategoryService.java
  src/main/java/com/example/gasip/exception/DuplicateResourceException.java
  src/main/java/com/example/gasip/global/entity/HttpResponseEntity.java
  src/main/java/com/example/gasip/likes/controller/LikeController.java
  src/main/java/com/example/gasip/likes/dto/LikeRequestDto.java
  src/main/java/com/example/gasip/likes/model/Likes.java
  src/main/java/com/example/gasip/likes/repository/LikeRepository.java
  src/main/java/com/example/gasip/likes/service/LikeService.java
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepository.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: enhancement, Backend

#125 Feature/#124 비로그인 사용자 조회 가능 기능 정리
  src/main/generated/com/example/gasip/likes/model/QLikes.java
  src/main/java/com/example/gasip/config/SecurityConfig.java
Labels: bug, enhancement, Backend

#126 Feature/#122 게시글 페이지네이션
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/college/dto/CollegeDto.java
  src/main/java/com/example/gasip/college/dto/CollegeResponse.java
  src/main/java/com/example/gasip/college/model/College.java
Labels: enhancement, Backend

#127 Feat : Board findAll 페이지네이션
  src/main/java/com/example/gasip/board/repository/BoardRepository.java
  src/main/java/com/example/gasip/board/service/BoardService.java
Labels: enhancement, Backend

#130 Feat: Authentification by Token Checking
  Gasip Front/Components/HomeScreen.js
  Gasip Front/Components/MyPageStack.js
  Gasip Front/Utils/AuthFunc.js
  Gasip Front/Utils/AuthHooks.js
  Gasip Front/Utils/Configuration.js
Labels: enhancement, Frontend
