Repository GASIP-PROJECT/gasip-backend, pull requests merged in 2024-06, with the labels that each got.

#338 [백엔드] findFreeBoardByProfessor, findBoardByAllProfessor 페이지네이션 추가
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
Labels: Backend, Refactoring

#339 모든 교수 리뷰, 자유게시판에 페이지네이션 추가 및 리팩토링
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
Labels: Backend, Refactoring

#343 Refactor : Board 내 중복 칼럼 제거
  src/main/generated/com/example/gasip/board/dto/QBoardReadResponse.java
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/dto/BoardProfessorReadResponse.java
  src/main/java/com/example/gasip/board/dto/BoardReadResponse.java
  src/main/java/com/example/gasip/board/dto/OneBoardReadResponse.java
  src/main/java/com/example/gasip/board/model/Board.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
Labels: bug, Backend

#344 Refactor : 트랜잭션 ReadOnly 추가
  src/main/java/com/example/gasip/board/service/BoardService.java
Labels: bug, Backend

#345 publish : Board 리팩토링
  src/main/generated/com/example/gasip/board/dto/QBoardReadResponse.java
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/dto/BoardProfessorReadResponse.java
  src/main/java/com/example/gasip/board/dto/BoardReadResponse.java
  src/main/java/com/example/gasip/board/dto/OneBoardReadResponse.java
  src/main/java/com/example/gasip/board/model/Board.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
Labels: publish

#348 Feat : firebase 의존성 추가
  .gitignore
  build.gradle
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/dto/BoardPushRequest.java
  src/main/java/com/example/gasip/board/service/FirebasePushService.java
  src/main/java/com/example/gasip/global/entity/FcmMessage.java
Labels: Backend

#350 publish : deploy.sh 수정
  .gitignore
  build.gradle
  deploy.sh
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/dto/BoardPushRequest.java
  src/main/java/com/example/gasip/board/service/FirebasePushService.java
  src/main/java/com/example/gasip/global/entity/FcmMessage.java
Labels: publish

#351 Update deploy.sh
  deploy.sh
Labels: Refactoring

#353 publish : 스레드 풀 변경 테스트
  README.md
Labels: publish

#355 Feat : FCM 알림 기능 구현
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/dto/BoardPushRequest.java
  src/main/java/com/example/gasip/board/dto/FcmMessageRequest.java
  src/main/java/com/example/gasip/board/service/FirebasePushService.java
Labels: Backend

#356 Publish : FCM 설정 추가
  .github/workflows/gradle.yml
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/dto/BoardPushRequest.java
  src/main/java/com/example/gasip/board/dto/FcmMessageRequest.java
  src/main/java/com/example/gasip/board/service/FirebasePushService.java
Labels: publish
