Repository GASIP-PROJECT/gasip-backend, pull requests merged in 2024-07, with the labels that each got.

#357 Feature/#349 인기글캐싱도입
  build.gradle
  src/main/java/com/example/gasip/board/dto/BoardReadResponse.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/board/service/RedisBestBoardService.java
  src/main/java/com/example/gasip/global/config/RedisCacheConfig.java
  src/main/java/com/example/gasip/global/config/RedisConfig.java
  src/main/java/com/example/gasip/global/entity/BaseTimeEntity.java
Labels: Backend

#358 publish : 인기글 캐싱 로직 배포 & 스레드풀 원상복귀
  build.gradle
  src/main/java/com/example/gasip/board/dto/BoardReadResponse.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/board/service/RedisBestBoardService.java
  src/main/java/com/example/gasip/global/config/RedisCacheConfig.java
  src/main/java/com/example/gasip/global/config/RedisConfig.java
  src/main/java/com/example/gasip/global/entity/BaseTimeEntity.java
Labels: publish

#360 Refactor : category 조회 api 구현 및 리팩토링
  .gitignore
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/category/dto/CategoryDto.java
  src/main/java/com/example/gasip/category/dto/CategoryResponse.java
  src/main/java/com/example/gasip/category/model/Category.java
  src/main/java/com/example/gasip/category/repository/CategoryRepository.java
  src/main/java/com/example/gasip/category/repository/CategoryRepositoryCustomImpl.java
  src/main/java/com/example/gasip/category/service/CategoryService.java
Labels: enhancement, Backend, Refactoring

#361 Feat : 인기글 등록 하루 초과 시 인기글에서 제외
  src/main/java/com/example/gasip/board/service/BoardService.java
Labels: enhancement, Backend

#364 HotFix : 교수 평점 소수점 버그 픽스
  src/main/java/com/example/gasip/grade/dto/response/GradeGetDto.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: bug, Backend

#365 publish : 교수 평점 소수점 에러 픽스
  src/main/java/com/example/gasip/grade/dto/response/GradeGetDto.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: publish

#367 HotFix : 게시글 조회 버그 픽스
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: bug, Backend

#368 publish : 게시판 조회 버그 픽스
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: publish

#369 HotFix : 평균 평점 로직 수정
  src/main/java/com/example/gasip/grade/dto/response/GradeGetDto.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: bug, Backend

#370 publish : 평균 평점 조회 로직 bugfix
  src/main/java/com/example/gasip/grade/dto/response/GradeGetDto.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: publish

#371 HotFix : 비밀번호 재설정 로직 호출 수정
  src/main/java/com/example/gasip/global/config/SecurityConfig.java
Labels: publish

#373 Bug : 자유게시판 조회 버그 해결
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/category/repository/CategoryRepository.java
Labels: bug, Backend

#375 Feat : 닉네임 중복 방지 로직 구현
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/global/config/RedisCacheConfig.java
  src/main/java/com/example/gasip/global/constant/ErrorCode.java
  src/main/java/com/example/gasip/global/exception/DuplicateMemberException.java
  src/main/java/com/example/gasip/global/exception/DuplicateNickNameException.java
  src/main/java/com/example/gasip/global/exception/InvalidVerifiedException.java
  src/main/java/com/example/gasip/global/exception/InvalidWritterException.java
  src/main/java/com/example/gasip/global/exception/NoSuchVerifiedCodeException.java
  src/main/java/com/example/gasip/member/repository/MemberRepository.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: Backend

#376 publish : 닉네임 중복 방지 로직 추가
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/global/config/RedisCacheConfig.java
  src/main/java/com/example/gasip/global/constant/ErrorCode.java
  src/main/java/com/example/gasip/global/exception/DuplicateMemberException.java
  src/main/java/com/example/gasip/global/exception/DuplicateNickNameException.java
  src/main/java/com/example/gasip/global/exception/InvalidVerifiedException.java
  src/main/java/com/example/gasip/global/exception/InvalidWritterException.java
  src/main/java/com/example/gasip/global/exception/NoSuchVerifiedCodeException.java
  src/main/java/com/example/gasip/member/repository/MemberRepository.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: publish

#378 Bug Fix : 커버링 인덱스 사용 시 1페이지 이상 조회되지 않는 버그
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
Labels: bug, Backend, Refactoring

#379 Publish : 자유게시판 조회 버그 해결
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
Labels: publish

#380 Fix : 자유게시판 size마다 게시글 달라지는 버그 수정
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
Labels: bug, Backend

#381 Publish : 자유게시판 페이지 별 조회 목록 달라지는 버그 수정
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
Labels: publish

#384 #383 알림비동기구현
  build.gradle
  src/main/java/com/example/gasip/board/service/FirebasePushService.java
  src/main/java/com/example/gasip/global/config/AsyncConfig.java
Labels: Backend

#386 CICD 파이프라인 테스트
  .github/workflows/stage.yml
Labels: publish

#387 CICD 테스트
  .github/workflows/stage.yml
Labels: Backend, publish

#389 fix key value
  .github/workflows/gradle.yml
Labels: invalid

#417 feat : stage 서버 디스코드 웹 훅 추가
  src/main/resources/logback-dev.xml
Labels: Backend

#418 디스코드 웹 훅 추가, 크롤링 api 뼈대 추가
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/service/FirebasePushService.java
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
  src/main/java/com/example/gasip/professor/dto/ProfessorCrawlRequest.java
  src/main/java/com/example/gasip/professor/service/ProfessorDataCrawlingService.java
  src/main/resources/logback-dev.xml
  src/test/java/com/example/gasip/board/service/BoardServiceTest.java
Labels: Backend

#420 stage.yml 수정
  .github/workflows/stage.yml
Labels: Backend

#421 fix : 변경 application.yml
  src/main/resources/logback-dev.xml
Labels: bug, Backend

#422 디스코드 웹 훅 버그 수정
  .github/workflows/stage.yml
  src/main/resources/logback-dev.xml
Labels: bug, Backend

#423 fix : 변경 logback.xml
  src/main/resources/logback-dev.xml
  src/main/resources/logback.xml
Labels: bug, Backend

#424 변경 logback.xml
  src/main/resources/logback-dev.xml
  src/main/resources/logback.xml
Labels: bug, Backend

#425 fix : error.log 추가
  scripts/start.sh
Labels: bug, documentation, Backend

#426 error.log 파일 작성 안되는 버그 수정
  scripts/start.sh
Labels: bug, Backend

#427 fix : start.sh 변경
  scripts/start.sh
Labels: bug, Backend

#428 start.sh 변경
  scripts/start.sh
Labels: bug, Backend

#429 fix : start.sh 변경
  scripts/start.sh
Labels: Backend, Refactoring

#430 nohup 배포 시 로그 기록 임시 삭제
  scripts/start.sh
Labels: Backend

#431 fix : start.sh 변경
  scripts/start.sh
Labels: bug, Backend

#432 배포 시 dev 환경에서 실행되도록 변경
  scripts/start.sh
Labels: Backend

#433 배포시 디스코드 웹 훅 알림 오지 않는 버그 수정
  scripts/start.sh
Labels: bug, Backend

#434 배포 시 디스코드 웹 훅을 통해 알림이 오지 않는 버그 수정
  scripts/start.sh
Labels: bug, Backend

#437 log-back.yml stage서버 username 변경
  src/main/resources/logback-dev.xml
Labels: Backend

#438 stage서버 디스코드 웹 훅 username 변경
  src/main/resources/logback-dev.xml
Labels: Backend, Refactoring

#439 Feat : 교수정보 크롤링 코드 추가
  src/main/java/com/example/gasip/professor/service/ProfessorDataCrawlingService.java
Labels: enhancement, Backend

#440 교수 크롤링 데이터 배포
  src/main/java/com/example/gasip/professor/service/ProfessorDataCrawlingService.java
Labels: Backend

#444 Feature/#414 교수정보크롤링
  build.gradle
  src/main/java/com/example/gasip/category/repository/CategoryRepository.java
  src/main/java/com/example/gasip/professor/dto/ProfessorCrawlRequest.java
  src/main/java/com/example/gasip/professor/model/Professor.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepository.java
  src/main/java/com/example/gasip/professor/service/ProfessorDataCrawlingService.java
  src/main/resources/logback.xml
Labels: Backend

#448 Refacor : 서버 확인
  scripts/start.sh
Labels: bug, Backend

#449 서버 확인
  scripts/start.sh
Labels: bug, Backend

#451 fix : stage 서버 디스코드 웹 훅 "운영 서버 에러"로 뜨는 버그 수정
  src/main/resources/logback-dev.xml
Labels: bug, Backend

#452 fix : stage 서버 디스코드 웹 훅 "운영 서버 에러"로 뜨는 버그 수정
  src/main/resources/logback-dev.xml
Labels: bug, Backend

#454 Feat : 인기글 조회 로직 임시변경
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/service/BoardService.java
Labels: Backend

#455 publish : 인기글 로직 임시 변경
  scripts/start.sh
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/resources/logback-dev.xml
Labels: publish

#457 hotfix : stage서버 디스코드 웹 훅 버그 수정
  src/main/resources/logback-dev.xml
Labels: bug, Backend
