Repository GASIP-PROJECT/gasip-backend, pull requests merged in 2024-04, with the labels that each got.

#208 Feat : 인증메일 발송 시 MimeMessage 클래스 활용
  build.gradle
  src/main/generated/com/example/gasip/grade/dto/response/QGradeGetDto.java
  src/main/generated/com/example/gasip/grade/model/QGrade.java
  src/main/java/com/example/gasip/member/service/MailService.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: enhancement, Backend

#209 이메일 인증 로직 추가
  build.gradle
  src/main/generated/com/example/gasip/board/dto/QBoardReadResponse.java
  src/main/generated/com/example/gasip/board/model/QBoard.java
  src/main/generated/com/example/gasip/category/dto/QCategoryResponse.java
  src/main/generated/com/example/gasip/category/model/QCategory.java
  src/main/generated/com/example/gasip/comment/model/QComment.java
  src/main/generated/com/example/gasip/global/entity/QBaseTimeEntity.java
  src/main/generated/com/example/gasip/grade/dto/response/QGradeGetDto.java
  src/main/generated/com/example/gasip/grade/model/QGrade.java
  src/main/generated/com/example/gasip/likes/model/QLikes.java
  src/main/generated/com/example/gasip/member/model/QMember.java
  src/main/generated/com/example/gasip/professor/model/QProfessor.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/board/service/RedisViewCountService.java
  src/main/java/com/example/gasip/global/config/EmailConfig.java
  src/main/java/com/example/gasip/global/config/SecurityConfig.java
  src/main/java/com/example/gasip/member/controller/MemberController.java
  src/main/java/com/example/gasip/member/service/MailService.java
  src/main/java/com/example/gasip/member/service/MemberService.java
  src/main/java/com/example/gasip/member/service/RedisMailService.java
Labels: enhancement, Backend

#213 Feature/#204 search
  src/main/generated/com/example/gasip/board/dto/QBoardReadResponse.java
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/dto/BoardContentDto.java
  src/main/java/com/example/gasip/board/dto/BoardReadResponse.java
  src/main/java/com/example/gasip/board/repository/BoardRepository.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/category/controller/CategoryController.java
  src/main/java/com/example/gasip/category/model/Category.java
  src/main/java/com/example/gasip/category/repository/CategoryRepository.java
  src/main/java/com/example/gasip/category/service/CategoryService.java
  src/main/java/com/example/gasip/global/config/RedissonConfig.java
  src/main/java/com/example/gasip/likes/controller/LikeController.java
  src/main/java/com/example/gasip/likes/service/LikeServiceInRedis.java
  src/main/java/com/example/gasip/member/controller/MemberController.java
  src/main/java/com/example/gasip/member/dto/MemberLogInRequest.java
  src/main/java/com/example/gasip/member/dto/MemberLogInResponse.java
  src/main/java/com/example/gasip/member/dto/MemberMyBoardResponse.java
  src/main/java/com/example/gasip/member/dto/MemberMyPageResponse.java
  src/main/java/com/example/gasip/member/dto/MemberSignUpRequest.java
  src/main/java/com/example/gasip/member/dto/MemberSignUpResponse.java
  src/main/java/com/example/gasip/member/model/Member.java
  src/main/java/com/example/gasip/redisson/CustomSpringELParser.java
  src/main/java/com/example/gasip/redisson/RedissonLock.java
  src/main/java/com/example/gasip/redisson/RedissonLockAspect.java
Labels: enhancement, Backend, Refactoring

#214 Refactor : 전체 글에서 인기글 조회하는 로직으로 변경
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/repository/BoardRepository.java
  src/main/java/com/example/gasip/board/service/BoardService.java
Labels: Backend, Refactoring

#216 HotFix : 교수별 게시글 조회 로직 누락으로 추가
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/repository/BoardRepository.java
  src/main/java/com/example/gasip/board/service/BoardService.java
Labels: bug, Backend

#219 Feature/#218 professor search
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepository.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: enhancement, Backend

#222 Refactor : 전체 인기글 조회로 변경
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
Labels: enhancement, Backend

#223 교수이름 검색 & 인기글 조회 로직 변경
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepository.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: Backend

#225 Feature/#224 board desc
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/repository/BoardRepository.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepository.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: Backend, Refactoring

#226 [백엔드] 전체 게시글 목록 조회 시 최근에 작성된 순으로 조회
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/repository/BoardRepository.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepository.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: Backend, Refactoring

#228 Feature/#224 board desc
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/repository/BoardRepository.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepository.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: Backend, Refactoring

#229 [백엔드] 검색 기능 사용 시 내림차순 정렬
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/repository/BoardRepository.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepository.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: Backend, Refactoring

#231 Feat : 회원가입 시 닉네임 칼럼 추가
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/global/constant/ErrorCode.java
  src/main/java/com/example/gasip/global/exception/MemberDuplicatedException.java
  src/main/java/com/example/gasip/member/controller/MemberController.java
  src/main/java/com/example/gasip/member/dto/MemberSignUpRequest.java
  src/main/java/com/example/gasip/member/dto/MemberSignUpResponse.java
  src/main/java/com/example/gasip/member/model/Member.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: Backend

#232 [배포] 회원가입 시 닉네임 칼럼 추가
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/global/constant/ErrorCode.java
  src/main/java/com/example/gasip/global/exception/MemberDuplicatedException.java
  src/main/java/com/example/gasip/member/controller/MemberController.java
  src/main/java/com/example/gasip/member/dto/MemberSignUpRequest.java
  src/main/java/com/example/gasip/member/dto/MemberSignUpResponse.java
  src/main/java/com/example/gasip/member/model/Member.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: Backend

#236 [백엔드] 전체 게시글 조회하는 기능 추가
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/category/controller/CategoryController.java
  src/main/java/com/example/gasip/category/repository/CategoryRepository.java
  src/main/java/com/example/gasip/category/repository/CategoryRepositoryCustomImpl.java
  src/main/java/com/example/gasip/category/service/CategoryService.java
Labels: enhancement, Backend, Refactoring

#243 Refactor : 게시글 조회 시 회원 정보를 고려하여 조회하도록 로직 완성
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/board/service/RedisViewCountService.java
Labels: Backend

#244 조회수 동시성 처리 리팩토링 배포
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/board/service/RedisViewCountService.java
Labels: publish

#245 Feat : 닉네임 변경 로직 구현
  src/main/java/com/example/gasip/member/controller/MemberController.java
  src/main/java/com/example/gasip/member/dto/MemberSignUpRequest.java
  src/main/java/com/example/gasip/member/dto/MemberSignUpResponse.java
  src/main/java/com/example/gasip/member/dto/MemberUpdateNicknameRequest.java
  src/main/java/com/example/gasip/member/dto/MemberUpdateNicknameResponse.java
  src/main/java/com/example/gasip/member/model/Member.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: Backend

#247 닉네임 수정로직
  src/main/java/com/example/gasip/member/controller/MemberController.java
  src/main/java/com/example/gasip/member/dto/MemberSignUpRequest.java
  src/main/java/com/example/gasip/member/dto/MemberSignUpResponse.java
  src/main/java/com/example/gasip/member/dto/MemberUpdateNicknameRequest.java
  src/main/java/com/example/gasip/member/dto/MemberUpdateNicknameResponse.java
  src/main/java/com/example/gasip/member/model/Member.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: publish

#248 Feat : 닉네임 변경, 비밀번호 변경, 회원 탈퇴 로직 추가
  src/main/java/com/example/gasip/member/controller/MemberController.java
  src/main/java/com/example/gasip/member/dto/MemberUpdatePasswordRequest.java
  src/main/java/com/example/gasip/member/dto/MemberUpdatePasswordResponse.java
  src/main/java/com/example/gasip/member/model/Member.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: enhancement, Backend

#249 회원정보 수정 api 추가
  src/main/java/com/example/gasip/member/controller/MemberController.java
  src/main/java/com/example/gasip/member/dto/MemberUpdatePasswordRequest.java
  src/main/java/com/example/gasip/member/dto/MemberUpdatePasswordResponse.java
  src/main/java/com/example/gasip/member/model/Member.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: publish

#250 Feat : 스웨거 태그 추가
  src/main/java/com/example/gasip/member/controller/MemberController.java
Labels: Backend

#251 스웨거 태그 추가 배포
  src/main/java/com/example/gasip/member/controller/MemberController.java
Labels: publish

#252 Feature/#246 professor refactor
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/dto/BoardProfessorReadResponse.java
  src/main/java/com/example/gasip/board/repository/BoardRepository.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
  src/main/java/com/example/gasip/professor/dto/ProfessorWithBoardResponse.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepository.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepositoryCustom.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepositoryCustomImpl.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: enhancement, Backend, Refactoring

#255 HotFix : CORS 에러 해결
  src/main/java/com/example/gasip/global/config/SecurityConfig.java
Labels: publish

#260 HotFix : 게시글 호출 시 닉네임 데이터 추가
  src/main/java/com/example/gasip/board/dto/BoardProfessorReadResponse.java
  src/main/java/com/example/gasip/board/dto/BoardReadResponse.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/professor/dto/ProfessorWithBoardResponse.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepositoryCustomImpl.java
Labels: Backend, Refactoring

#262 마이페이지 응답칼럼 수정 배포
  src/main/generated/com/example/gasip/board/dto/QBoardReadResponse.java
  src/main/java/com/example/gasip/member/dto/MemberMyPageResponse.java
Labels: publish

#263 Feature/#204 like error
  src/main/java/com/example/gasip/likes/service/LikeService.java
Labels: Backend, Refactoring

#264 [백엔드] 좋아요 재요청시 에러 반환
  src/main/java/com/example/gasip/likes/service/LikeService.java
Labels: Backend, Refactoring

#265 [백엔드] Refacor : 좋아요 요청 시 헤더에서 memberId 받도록 수정
  src/main/java/com/example/gasip/likes/dto/LikeRequestDto.java
Labels: Backend, Refactoring

#266 [백엔드] 좋아요 요청 시 헤더에서 memberId 받도록 수정
  src/main/java/com/example/gasip/likes/dto/LikeRequestDto.java
Labels: Backend, Refactoring

#268 Feature/#267 교수 조회/로그인/게시글 조회 시 필요 칼럼 추가
  src/main/generated/com/example/gasip/board/dto/QBoardReadResponse.java
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/dto/BoardReadResponse.java
  src/main/java/com/example/gasip/board/dto/OneBoardReadResponse.java
  src/main/java/com/example/gasip/board/model/Board.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/comment/dto/CommentChildrenReadResponse.java
  src/main/java/com/example/gasip/comment/dto/CommentReadResponse.java
  src/main/java/com/example/gasip/member/dto/MemberLogInResponse.java
  src/main/java/com/example/gasip/professor/dto/ProfessorResponse.java
Labels: enhancement, Backend

#269 프론트 작업 시 필요 칼럼 추가 후 배포
  src/main/generated/com/example/gasip/board/dto/QBoardReadResponse.java
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/dto/BoardReadResponse.java
  src/main/java/com/example/gasip/board/dto/OneBoardReadResponse.java
  src/main/java/com/example/gasip/board/model/Board.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/comment/dto/CommentChildrenReadResponse.java
  src/main/java/com/example/gasip/comment/dto/CommentReadResponse.java
  src/main/java/com/example/gasip/member/dto/MemberLogInResponse.java
  src/main/java/com/example/gasip/professor/dto/ProfessorResponse.java
Labels: publish

#270 Hotfix : BoardReadResponse Q파일 수정 배포
  src/main/generated/com/example/gasip/board/dto/QBoardReadResponse.java
  src/main/java/com/example/gasip/board/dto/BoardReadResponse.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
Labels: publish

#272 HotFix : Board 상세정보 호출 시 닉네임 칼럼 추가
  src/main/java/com/example/gasip/board/dto/OneBoardReadResponse.java
Labels: Backend, Refactoring

#274 Refactor : 게시글 조회 시 응답데이터 칼럼 추가
  src/main/generated/com/example/gasip/board/dto/QBoardReadResponse.java
  src/main/java/com/example/gasip/board/dto/BoardReadResponse.java
  src/main/java/com/example/gasip/board/dto/OneBoardReadResponse.java
Labels: Backend, Refactoring

#275 Refactor : BoardReadResponse Q파일 수정
  src/main/generated/com/example/gasip/board/dto/QBoardReadResponse.java
  src/main/java/com/example/gasip/board/dto/BoardReadResponse.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
Labels: Backend, Refactoring

#276 게시글 응답 데이터 칼럼 추가 배포
  src/main/generated/com/example/gasip/board/dto/QBoardReadResponse.java
  src/main/java/com/example/gasip/board/dto/BoardReadResponse.java
  src/main/java/com/example/gasip/board/dto/OneBoardReadResponse.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
Labels: publish

#279 [백엔드] 좋아요 눌렀는지 확인하는 컬럼 Board 컬럼에 추가
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/dto/OneBoardReadResponse.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/global/constant/ErrorCode.java
  src/main/java/com/example/gasip/global/exception/DuplicateResourceException.java
  src/main/java/com/example/gasip/global/exception/handler/GlobalControllerAdvice.java
  src/main/java/com/example/gasip/likes/controller/LikeController.java
  src/main/java/com/example/gasip/likes/dto/LikeRequestDto.java
  src/main/java/com/example/gasip/likes/dto/LikeResponseDto.java
  src/main/java/com/example/gasip/likes/repository/LikeRepository.java
  src/main/java/com/example/gasip/likes/service/LikeService.java
Labels: enhancement, Backend, Refactoring

#280 게시글 좋아요 클릭 여부 배포
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/dto/OneBoardReadResponse.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/global/constant/ErrorCode.java
  src/main/java/com/example/gasip/global/exception/DuplicateResourceException.java
  src/main/java/com/example/gasip/global/exception/handler/GlobalControllerAdvice.java
  src/main/java/com/example/gasip/likes/controller/LikeController.java
  src/main/java/com/example/gasip/likes/dto/LikeRequestDto.java
  src/main/java/com/example/gasip/likes/dto/LikeResponseDto.java
  src/main/java/com/example/gasip/likes/repository/LikeRepository.java
  src/main/java/com/example/gasip/likes/service/LikeService.java
Labels: publish

#281 publish : BoardReadResponse Q파일 수정
  src/main/java/com/example/gasip/board/dto/OneBoardReadResponse.java
Labels: publish

#284 Feat : 비밀번호 재설정 시 이메일 인증 api
  src/main/java/com/example/gasip/member/controller/MemberController.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: enhancement, Backend

#285 publish : 기존이메일인증로직 배포
  src/main/java/com/example/gasip/member/controller/MemberController.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: Backend, publish

#287 Feat : CommentLike 도메인생성 및 내가쓴글 응답 정보 추가
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/dto/OneBoardReadResponse.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/commentLikes/controller/CommentLikesController.java
  src/main/java/com/example/gasip/commentLikes/dto/CommentLikesRequestDto.java
  src/main/java/com/example/gasip/commentLikes/model/CommentLikes.java
  src/main/java/com/example/gasip/commentLikes/repository/CommentLikesRepository.java
  src/main/java/com/example/gasip/commentLikes/service/CommentLikesService.java
  src/main/java/com/example/gasip/global/redisson/CustomSpringELParser.java
  src/main/java/com/example/gasip/global/redisson/RedissonLock.java
  src/main/java/com/example/gasip/global/redisson/RedissonLockAspect.java
  src/main/java/com/example/gasip/likes/service/LikeServiceInRedis.java
  src/main/java/com/example/gasip/member/controller/MemberController.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: enhancement, Backend

#288 publish 마이페이지응답정보변경 배포
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/dto/OneBoardReadResponse.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/commentLikes/controller/CommentLikesController.java
  src/main/java/com/example/gasip/commentLikes/dto/CommentLikesRequestDto.java
  src/main/java/com/example/gasip/commentLikes/model/CommentLikes.java
  src/main/java/com/example/gasip/commentLikes/repository/CommentLikesRepository.java
  src/main/java/com/example/gasip/commentLikes/service/CommentLikesService.java
  src/main/java/com/example/gasip/global/redisson/CustomSpringELParser.java
  src/main/java/com/example/gasip/global/redisson/RedissonLock.java
  src/main/java/com/example/gasip/global/redisson/RedissonLockAspect.java
  src/main/java/com/example/gasip/likes/service/LikeServiceInRedis.java
  src/main/java/com/example/gasip/member/controller/MemberController.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: publish

#293 Feature/#292 인기글응답칼럼수정
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: Backend, Refactoring

#295 [백엔드] 게시글 조회 시 isCommentLike 칼럼 추가
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/comment/dto/CommentReadResponse.java
  src/main/java/com/example/gasip/commentLikes/repository/CommentLikesRepository.java
Labels: bug, Backend, Refactoring

#297 HotFix : 교수 String 검색 시 교수평점 안나오는 에러 해결
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: Backend, Refactoring

#298 publish : 교수 String 검색 시 교수평점 안나오는 에러 해결
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/comment/dto/CommentReadResponse.java
  src/main/java/com/example/gasip/commentLikes/repository/CommentLikesRepository.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: publish

#299 HotFix : 교수 String 검색 시 평점 등록 여부 칼럼 추가
  src/main/java/com/example/gasip/grade/repository/GradeRepository.java
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
  src/main/java/com/example/gasip/professor/dto/ProfessorResponse.java
  src/main/java/com/example/gasip/professor/model/Professor.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: Backend, Refactoring

#300 publish : isGrade 칼럼 추가
  src/main/java/com/example/gasip/grade/repository/GradeRepository.java
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
  src/main/java/com/example/gasip/professor/dto/ProfessorResponse.java
  src/main/java/com/example/gasip/professor/model/Professor.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: publish

#301 HotFix : 교수 Id 검색 시 평점 등록 여부 칼럼 추가
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: Backend, Refactoring

#302 publish : 교수Id 검색 시 isGrade 칼럼 추가
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: Backend, publish

#305 [백엔드] HotFix 게시글 호출 시 댓글 필드 수정
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/comment/dto/CommentChildrenReadResponse.java
  src/main/java/com/example/gasip/comment/dto/CommentReadResponse.java
Labels: bug, Backend, Refactoring

#306 publish : 게시글 호출 시 댓글 필드 수정
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/comment/dto/CommentChildrenReadResponse.java
  src/main/java/com/example/gasip/comment/dto/CommentReadResponse.java
Labels: publish
