Repository GASIP-PROJECT/gasip-backend, pull requests merged in 2024-08, with the labels that each got.

#458 Feat : Education 칼럼 추가
  src/main/java/com/example/gasip/professor/dto/ProfessorResponse.java
  src/main/java/com/example/gasip/professor/model/Professor.java
Labels: Backend

#460 publish : professor 칼럼 추가 및 인기글 로직 임시 변경
  README.md
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/professor/dto/ProfessorResponse.java
  src/main/java/com/example/gasip/professor/model/Professor.java
  src/main/resources/logback-dev.xml
Labels: publish

#461 publish : 인기글 로직 미변경 확인
  src/main/java/com/example/gasip/board/service/BoardService.java
Labels: publish

#462 publish : 인기글 로직 임시설정 테스트
  src/main/java/com/example/gasip/board/service/BoardService.java
Labels: publish

#464 publish : appspec.yml 수정
  appspec.yml
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/service/BoardService.java
Labels: publish

#466 Feat : deploy.sh 수정
  deploy.sh
Labels: publish

#467 Feat : logback.xml 수정
  src/main/resources/logback.xml
Labels: publish

#469 Refactor : 카테고리 도메인 내 사용하지 않는 api 정리 및 querydsl 리팩토링
  src/main/java/com/example/gasip/category/controller/CategoryController.java
  src/main/java/com/example/gasip/category/repository/CategoryRepository.java
  src/main/java/com/example/gasip/category/repository/CategoryRepositoryCustom.java
  src/main/java/com/example/gasip/category/service/CategoryService.java
Labels: Backend, Refactoring

#470 fix : stgae 서버 배포를 위해 appspec.yml 임시 변경
  appspec.yml
Labels: publish

#471 publish : 카테고리 도메인 완성
  README.md
  deploy.sh
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/category/controller/CategoryController.java
  src/main/java/com/example/gasip/category/repository/CategoryRepository.java
  src/main/java/com/example/gasip/category/repository/CategoryRepositoryCustom.java
  src/main/java/com/example/gasip/category/service/CategoryService.java
  src/main/java/com/example/gasip/professor/dto/ProfessorResponse.java
  src/main/java/com/example/gasip/professor/model/Professor.java
  src/main/resources/logback-dev.xml
  src/main/resources/logback.xml
Labels: Backend, Refactoring, publish

#473 fix : appspec.yml 변경
  appspec.yml
Labels: Backend

#476 publish : 회원가입 인증번호 코드 임시 고정
  .github/workflows/stage.yml
  src/main/java/com/example/gasip/category/controller/CategoryController.java
  src/main/java/com/example/gasip/category/repository/CategoryRepository.java
  src/main/java/com/example/gasip/category/repository/CategoryRepositoryCustom.java
  src/main/java/com/example/gasip/category/service/CategoryService.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: publish

#477 feat : 게시글 및 댓글 신고 기능 구현
  appspec.yml
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/dto/BoardActivityRequestDto.java
  src/main/java/com/example/gasip/board/dto/BoardActivityResponseDto.java
  src/main/java/com/example/gasip/board/dto/BoardCreateRequest.java
  src/main/java/com/example/gasip/board/dto/BoardCreateResponse.java
  src/main/java/com/example/gasip/board/model/Board.java
  src/main/java/com/example/gasip/board/model/ContentActivity.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/boardReport/controller/BoardReportController.java
  src/main/java/com/example/gasip/boardReport/dto/BoardReportRequestDto.java
  src/main/java/com/example/gasip/boardReport/dto/BoardReportResponseDto.java
  src/main/java/com/example/gasip/boardReport/model/BoardReport.java
  src/main/java/com/example/gasip/boardReport/repository/BoardReportRepository.java
  src/main/java/com/example/gasip/boardReport/service/BoardReportService.java
  src/main/java/com/example/gasip/comment/dto/CommentChildrenReadResponse.java
  src/main/java/com/example/gasip/comment/dto/CommentCreateRequest.java
  src/main/java/com/example/gasip/comment/dto/CommentReadResponse.java
  src/main/java/com/example/gasip/comment/model/Comment.java
  src/main/java/com/example/gasip/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/example/gasip/comment/repository/CommentRepositoryCustomImpl.java
  src/main/java/com/example/gasip/commentReport/controller/CommentReportController.java
  src/main/java/com/example/gasip/commentReport/dto/CommentReportRequestDto.java
  src/main/java/com/example/gasip/commentReport/dto/CommentReportResponseDto.java
  src/main/java/com/example/gasip/commentReport/model/CommentReport.java
  src/main/java/com/example/gasip/commentReport/repository/CommentReportRepository.java
  src/main/java/com/example/gasip/commentReport/service/CommentReportService.java
  src/main/java/com/example/gasip/global/constant/ErrorCode.java
  src/main/java/com/example/gasip/global/exception/CheckFlaggedException.java
  src/main/java/com/example/gasip/global/exception/SelfBoardReportException.java
  src/main/java/com/example/gasip/global/exception/handler/DuplicateReportException.java
Labels: enhancement, Backend, Refactoring

#478 publish : 신고하기 기능 추가 및 인증번호 고정
  README.md
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/dto/BoardActivityRequestDto.java
  src/main/java/com/example/gasip/board/dto/BoardActivityResponseDto.java
  src/main/java/com/example/gasip/board/dto/BoardCreateRequest.java
  src/main/java/com/example/gasip/board/dto/BoardCreateResponse.java
  src/main/java/com/example/gasip/board/model/Board.java
  src/main/java/com/example/gasip/board/model/ContentActivity.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/boardReport/controller/BoardReportController.java
  src/main/java/com/example/gasip/boardReport/dto/BoardReportRequestDto.java
  src/main/java/com/example/gasip/boardReport/dto/BoardReportResponseDto.java
  src/main/java/com/example/gasip/boardReport/model/BoardReport.java
  src/main/java/com/example/gasip/boardReport/repository/BoardReportRepository.java
  src/main/java/com/example/gasip/boardReport/service/BoardReportService.java
  src/main/java/com/example/gasip/comment/dto/CommentChildrenReadResponse.java
  src/main/java/com/example/gasip/comment/dto/CommentCreateRequest.java
  src/main/java/com/example/gasip/comment/dto/CommentReadResponse.java
  src/main/java/com/example/gasip/comment/model/Comment.java
  src/main/java/com/example/gasip/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/example/gasip/comment/repository/CommentRepositoryCustomImpl.java
  src/main/java/com/example/gasip/commentReport/controller/CommentReportController.java
  src/main/java/com/example/gasip/commentReport/dto/CommentReportRequestDto.java
  src/main/java/com/example/gasip/commentReport/dto/CommentReportResponseDto.java
  src/main/java/com/example/gasip/commentReport/model/CommentReport.java
  src/main/java/com/example/gasip/commentReport/repository/CommentReportRepository.java
  src/main/java/com/example/gasip/commentReport/service/CommentReportService.java
  src/main/java/com/example/gasip/global/constant/ErrorCode.java
  src/main/java/com/example/gasip/global/exception/CheckFlaggedException.java
  src/main/java/com/example/gasip/global/exception/SelfBoardReportException.java
  src/main/java/com/example/gasip/global/exception/handler/DuplicateReportException.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: Backend, publish

#481 publish : 배포 main 서버 배포를 위한 appspec.yml 변경
  appspec.yml
Labels: Backend, publish
