Repository GASIP-PROJECT/gasip-backend, pull requests merged in 2024-03, with the labels that each got.

#138 Feat : 게시글 전체 조회 페이지네이션 적용
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/repository/BoardRepository.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/config/SecurityConfig.java
Labels: bug, enhancement

#139 Feat : 자유게시판 글 작성 api 개발
  src/main/java/com/example/gasip/freefeed/controller/FreefeedController.java
  src/main/java/com/example/gasip/freefeed/dto/FeedCreateRequest.java
  src/main/java/com/example/gasip/freefeed/dto/FeedCreateResponse.java
  src/main/java/com/example/gasip/freefeed/model/Freefeed.java
  src/main/java/com/example/gasip/freefeed/repository/FreefeedRepository.java
  src/main/java/com/example/gasip/freefeed/service/FreefeedService.java
Labels: enhancement, Backend

#140 Feat : Board 교수별 베스트 게시글 조회 api 개발
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/model/Board.java
  src/main/java/com/example/gasip/board/repository/BoardRepository.java
  src/main/java/com/example/gasip/board/service/BoardService.java
Labels: enhancement, Backend

#141 Feat : 교수 평점 칼럼 추가
  src/main/generated/com/example/gasip/board/dto/QBoardReadResponse.java
  src/main/generated/com/example/gasip/board/model/QBoard.java
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/dto/BoardCreateRequest.java
  src/main/java/com/example/gasip/board/dto/BoardCreateResponse.java
  src/main/java/com/example/gasip/board/dto/BoardReadResponse.java
  src/main/java/com/example/gasip/board/model/Board.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
Labels: enhancement, Backend

#142 Feat : 교수 평균 평점 조회 로직 추가
  src/main/java/com/example/gasip/board/repository/BoardRepository.java
  src/main/java/com/example/gasip/professor/dto/ProfessorResponse.java
  src/main/java/com/example/gasip/professor/model/Professor.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: enhancement, Backend

#144 Feat : FreeFeed 도메인 삭제
  src/main/java/com/example/gasip/freefeed/controller/FreefeedController.java
  src/main/java/com/example/gasip/freefeed/dto/FeedCreateRequest.java
  src/main/java/com/example/gasip/freefeed/dto/FeedCreateResponse.java
  src/main/java/com/example/gasip/freefeed/model/Freefeed.java
  src/main/java/com/example/gasip/freefeed/repository/FreefeedRepository.java
  src/main/java/com/example/gasip/freefeed/service/FreefeedService.java
Labels: Backend

#145 Feat : Board Test 클래스 생성
  src/test/java/com/example/gasip/board/controller/BoardControllerTest.java
Labels: Backend

#151 Feat : Board 컨트롤러 유닛 테스트 작성
  src/main/java/com/example/gasip/board/dto/BoardUpdateResponse.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/test/java/com/example/gasip/board/controller/BoardControllerTest.java
Labels: enhancement, Backend

#155 Refactor : 1개 계정으로 5분 내 조회수 중복 증가 불가 로직 구현
  build.gradle
  src/main/java/com/example/gasip/GasipApplication.java
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/board/service/RedisViewCountService.java
  src/main/java/com/example/gasip/global/config/QuerydslConfig.java
  src/main/java/com/example/gasip/global/config/SecurityConfig.java
  src/main/java/com/example/gasip/global/exception/BoardNotFoundException.java
  src/main/java/com/example/gasip/global/exception/CommentNotFoundException.java
  src/main/java/com/example/gasip/global/exception/DuplicateResourceException.java
  src/main/java/com/example/gasip/likes/service/LikeService.java
  src/test/java/com/example/config/SecurityConfigTest.java
  src/test/java/com/example/gasip/board/controller/BoardControllerTest.java
Labels: enhancement, Backend

#157 Refactor/#156 분산락구현
  build.gradle
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/model/Board.java
  src/main/java/com/example/gasip/board/service/BoardLockFacade.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/test/java/com/example/gasip/board/service/BoardServiceTest.java
Labels: enhancement, Backend

#158 Refactor : Professor 도메인 리팩토링
  src/main/java/com/example/gasip/board/service/BoardLockFacade.java
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
  src/main/java/com/example/gasip/professordetail/controller/ProfessorDetailController.java
  src/main/java/com/example/gasip/professordetail/dto/ProfessorDetailResponse.java
  src/main/java/com/example/gasip/professordetail/model/ProfessorDetail.java
  src/main/java/com/example/gasip/professordetail/repository/ProfessorDetailRepository.java
  src/main/java/com/example/gasip/professordetail/service/ProfessorDetailService.java
Labels: enhancement, Backend

#163 Feat : 평점 도메인 분리
  build.gradle
  src/main/java/com/example/gasip/grade/controller/GradeController.java
  src/main/java/com/example/gasip/grade/dto/request/GradeCreateRequest.java
  src/main/java/com/example/gasip/grade/dto/response/GradeCreateResponse.java
  src/main/java/com/example/gasip/grade/model/Grade.java
  src/main/java/com/example/gasip/grade/repository/GradeRepository.java
  src/main/java/com/example/gasip/grade/service/GradeService.java
Labels: enhancement, Backend

#164 College Category 테이블 내 단과대 데이터 중복으로 인한 API 병합
  src/main/generated/com/example/gasip/category/dto/QCategoryResponse.java
  src/main/java/com/example/gasip/board/dto/BoardReadRequest.java
  src/main/java/com/example/gasip/category/controller/CategoryController.java
  src/main/java/com/example/gasip/category/dto/CategoryResponse.java
  src/main/java/com/example/gasip/category/model/Category.java
  src/main/java/com/example/gasip/category/repository/CategoryRepository.java
  src/main/java/com/example/gasip/category/repository/CategoryRepositoryCustom.java
  src/main/java/com/example/gasip/category/repository/CategoryRepositoryCustomImpl.java
  src/main/java/com/example/gasip/category/service/CategoryService.java
Labels: Backend

#184 Feature/#183 merge major college
  src/main/generated/com/example/gasip/college/model/QCollege.java
  src/main/generated/com/example/gasip/major/model/QMajor.java
  src/main/generated/com/example/gasip/professor/model/QProfessor.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/college/controller/CollegeController.java
  src/main/java/com/example/gasip/college/dto/CollegeResponse.java
  src/main/java/com/example/gasip/college/model/College.java
  src/main/java/com/example/gasip/college/repository/CollegeRepository.java
  src/main/java/com/example/gasip/college/service/CollegeService.java
  src/main/java/com/example/gasip/global/config/SecurityConfig.java
  src/main/java/com/example/gasip/global/swagger/swaggerConfig.java
  src/main/java/com/example/gasip/likes/controller/LikeController.java
  src/main/java/com/example/gasip/likes/dto/LikeRequestDto.java
  src/main/java/com/example/gasip/likes/service/LikeService.java
  src/main/java/com/example/gasip/major/controller/MajorController.java
  src/main/java/com/example/gasip/major/dto/MajorResponse.java
  src/main/java/com/example/gasip/major/model/Major.java
  src/main/java/com/example/gasip/major/repository/MajorRepository.java
  src/main/java/com/example/gasip/major/service/MajorService.java
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
  src/main/java/com/example/gasip/professor/dto/ProfessorDto.java
  src/main/java/com/example/gasip/professor/dto/ProfessorResponse.java
  src/main/java/com/example/gasip/professor/model/Professor.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepository.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: Backend, Refactoring

#190 Feat : 디스코드 웹훅 적용
  Dockerfile
  build.gradle
  src/main/resources/logback.xml
Labels: Backend

#191 디스코드 웹훅 설정 추가
  Dockerfile
  build.gradle
  src/main/resources/logback.xml
Labels: Backend

#192 Refactor : 디스코드 웹훅 적용
  build.gradle
Labels: bug, Backend

#193 디스코드 웹훅 의존성 변경
  build.gradle
Labels: bug, Backend

#194 Refactor : 디스코드 웹훅 적용
  build.gradle
Labels: bug, Backend

#198 디스코드 웹훅 로컬/서버 환경 분리
  .gitignore
  src/main/resources/logback.xml
Labels: enhancement, Backend

#199 Update gradle.yml
  .github/workflows/gradle.yml
Labels: bug, Backend

#200 Update deploy.sh
  deploy.sh
Labels: bug, Backend

#201 Update deploy.sh
  deploy.sh
Labels: bug, Backend
