Repository GASIP-PROJECT/gasip-backend, pull requests merged in 2024-05, with the labels that each got.

#308 Refactor : 추가 nickname 필드
  src/main/java/com/example/gasip/member/dto/MemberLogInResponse.java
Labels: Backend, Refactoring

#309 publish : 추가 nickname 필드
  src/main/java/com/example/gasip/member/dto/MemberLogInResponse.java
Labels: Backend, Refactoring

#310 Refactor : 대댓글 응답 데이터에 닉네임 추가
  src/main/java/com/example/gasip/comment/dto/CommentChildrenReadResponse.java
Labels: Backend, Refactoring

#311 리팩토링 내역 배포
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/repository/BoardRepository.java
  src/main/java/com/example/gasip/board/service/BoardService.java
  src/main/java/com/example/gasip/comment/dto/CommentChildrenReadResponse.java
Labels: publish

#312 Refactor : 댓글 응답데이터 수정
  src/main/java/com/example/gasip/comment/dto/CommentReadResponse.java
Labels: enhancement, Backend

#315 Feat : 비로그인 시 비밀번호 변경 로직 추가
  src/main/java/com/example/gasip/member/controller/MemberController.java
  src/main/java/com/example/gasip/member/dto/MemberResetPasswordRequest.java
  src/main/java/com/example/gasip/member/dto/MemberResetPasswordResponse.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: enhancement, Backend

#316 로그인화면에서 비밀번호 변경 로직 추가하여 배포
  src/main/java/com/example/gasip/member/controller/MemberController.java
  src/main/java/com/example/gasip/member/dto/MemberResetPasswordRequest.java
  src/main/java/com/example/gasip/member/dto/MemberResetPasswordResponse.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: publish

#318 Refactor : 추가 regDate 기준 내림차순 정렬
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
Labels: Backend, Refactoring

#319 내가 쓴 글 정렬기준 수정 배포
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
Labels: Backend, Refactoring

#321 [백엔드] 학과/전공 키워드를 통한 교수 검색 기능
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
  src/main/java/com/example/gasip/professor/dto/ProfessorResponse.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepositoryCustom.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepositoryCustomImpl.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: enhancement, Backend, Refactoring

#322 학과/전공 키워드를 통한 교수 검색 기능 추가
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
  src/main/java/com/example/gasip/professor/dto/ProfessorResponse.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepositoryCustom.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepositoryCustomImpl.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: enhancement, Backend, publish

#324 Refactor : 회원 탈퇴 시 soft delete로 동작하도록 변경
  src/main/java/com/example/gasip/global/constant/ErrorCode.java
  src/main/java/com/example/gasip/member/controller/MemberController.java
  src/main/java/com/example/gasip/member/dto/MemberSignUpRequest.java
  src/main/java/com/example/gasip/member/model/Member.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: Backend, Refactoring

#325 리드미 작성 & 회원 softDelete 기능 리팩토링
  README.md
  src/main/java/com/example/gasip/global/constant/ErrorCode.java
  src/main/java/com/example/gasip/member/controller/MemberController.java
  src/main/java/com/example/gasip/member/dto/MemberSignUpRequest.java
  src/main/java/com/example/gasip/member/model/Member.java
  src/main/java/com/example/gasip/member/service/MemberService.java
Labels: publish

#327 Refactor : 추가 전체 검색 시 response 데이터에 null 값 return
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: Backend, Refactoring

#328 [백엔드] 키워드 '전체' 검색 시 빈 객체 반환하도록 변경
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepositoryCustom.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepositoryCustomImpl.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: Backend, Refactoring

#329 Refactor : 추가 교수 검색 시 averageGradePoint 칼럼 추가
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: Backend, Refactoring

#330 Refactor, Doc : 변경 /search -> /prof-search, 추가 prof-search Doc
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
Labels: documentation, Backend, Refactoring

#331 검색 기능 리팩토링
  src/main/java/com/example/gasip/grade/repository/GradeRepositoryCustomImpl.java
  src/main/java/com/example/gasip/professor/controller/ProfessorController.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepositoryCustom.java
  src/main/java/com/example/gasip/professor/repository/ProfessorRepositoryCustomImpl.java
  src/main/java/com/example/gasip/professor/service/ProfessorService.java
Labels: documentation, Backend, Refactoring

#334 모든 교수 리뷰 불러오는 기능, 모든 자유 게시글 불러오는 기능 추가
  src/main/java/com/example/gasip/board/controller/BoardController.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
Labels: enhancement, Backend, Refactoring

#335 Refactor : 변경 BoardProfessorReadResponse에서 BoardReadResponse로 Dto 변경 …
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
Labels: Backend, Refactoring

#336 모든 교수 리뷰, 자유 게시글 reponse에 isLike 칼럼 추가
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
  src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/example/gasip/board/service/BoardService.java
Labels: Backend, Refactoring
